CREATE DATABSE knot;

CREATE TABLE USERS (
    id INTEGER AUTOINCREMENT,
    FIRST_NAME TEXT,
    LAST_NAME TEXT,
    MOBILE TEXT,
    DOB TEXT,
    GENDER TEXT,
    EMAIL TEXT,
    ADDRESS TEXT,
    CITY TEXT,
    USERNAME TEXT PRIMARY KEY,
    PASSWORD TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);